repos: 
  - repo: local
    hooks:
      - id: lint
        name: Run lint via Makefile
        entry: make lint
        language: system
        files: ^src/,^test/
        types: [file, python]
        always_run: true
        pass_filenames: false
        
      - id: formatter
        name: Run black formatter via Makefile
        entry: make format
        language: system
        files: ^src/,^test/
        types: [file, python]
        always_run: true
        pass_filenames: false