repos: 
  - repo: local
    hooks:
      - id: validate
        name: Run lint and black via Makefile
        entry: make validate
        language: system
        files: ^src/,^test/
        types: [file, python]
        always_run: true
        pass_filenames: false